name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the package
        run: |
          source .venv/bin/activate
          python setup.py sdist bdist_wheel

      - name: Run Tests and coverage
        env:
            OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
            if [ -n "$OPENWEATHER_API_KEY" ]; then
                echo "API Key is set and has a length of ${#OPENWEATHERMAP_API_KEY} characters."
            else
                echo "API Key is not set."
            fi
            source .venv/bin/activate
            mkdir -p coverage_html_report
            coverage run -m pytest tests
